apiVersion: v1
kind: Secret
metadata:
  name: vista-secrets
  namespace: vista
type: Opaque
stringData:
  POSTGRES_PASSWORD: "vista_dev_2024"
  MINIO_ACCESS_KEY: "vistaadmin"
  MINIO_SECRET_KEY: "vistaSecretKey2024"
  SECRET_KEY: "vista-jwt-secret-change-in-prod"
