apiVersion: v1
kind: ConfigMap
metadata:
  name: vista-config
  namespace: vista
data:
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "vista"
  POSTGRES_DB: "vista"
  REDIS_URL: "redis://redis:6379/0"
  CELERY_BROKER_URL: "redis://redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis:6379/1"
  MINIO_ENDPOINT: "minio:9000"
  MINIO_BUCKET_IMAGES: "images-raw"
  MINIO_BUCKET_THUMBNAILS: "thumbnails"
  MINIO_BUCKET_MODELS: "models-weights"
  MINIO_BUCKET_EXPORTS: "exports"
  MLFLOW_TRACKING_URI: "http://mlflow:5000"
  DEVICE: "cpu"
  GIT_PYTHON_REFRESH: "quiet"
  APP_VERSION: "4.2"
