'use strict';

// Shared .env resolution for local dev tooling (dev-server.js, generate-environment.js):
// reads UI_PORT/API_PORT from the repo-root .env (single source of truth, see
// ../../.env.example) or from the process environment (e.g. docker-compose's
// env_file), so nothing needs to be hardcoded or regenerated by hand per developer.

const fs = require('fs');
const path = require('path');
const dotenv = require('dotenv');

const REPO_ROOT = path.join(__dirname, '..', '..');

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return {};
  return dotenv.parse(fs.readFileSync(filePath));
}

const rootEnv = parseEnvFile(path.join(REPO_ROOT, '.env'));

function resolve(name, fallback) {
  return process.env[name] || rootEnv[name] || fallback;
}

function resolvePort(name, fallback) {
  const value = resolve(name, fallback);
  if (!/^\d+$/.test(value)) {
    console.error(`Invalid ${name} value in .env: ${JSON.stringify(value)} (expected a number)`);
    process.exit(1);
  }
  return value;
}

module.exports = { resolve, resolvePort };
