"""initial app schema

Revision ID: 63d06542c8c0
Revises: 
Create Date: 2026-07-07 11:46:26.872262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63d06542c8c0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


DEFECT_CLASS_SEED: list[dict[str, str]] = [
    {"label": "Rayure profonde"},
    {"label": "Fissure (micro)"},
    {"label": "Décoloration / Tâche"},
    {"label": "Défaut d'usinage (Bavure)"},
    {"label": "Pièce manquante"},
]

defect_classes_table = sa.table(
    "defect_classes",
    sa.column("label", sa.String),
    schema="app",
)


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS app")
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defect_classes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label'),
    schema='app'
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), server_default='annotator', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='app'
    )
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app.users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='app'
    )
    op.create_table('images',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('image_hash', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'draft', 'ready', name='image_status', schema='app', create_constraint=True), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app.users.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['app.datasets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_hash'),
    schema='app'
    )
    op.create_index(op.f('ix_app_images_dataset_id'), 'images', ['dataset_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_images_status'), 'images', ['status'], unique=False, schema='app')
    op.create_table('annotations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('defect_class_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Enum('Critique', 'Majeur', 'Mineur', name='annotation_severity', schema='app', create_constraint=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('geometry_type', sa.Enum('bbox', 'polygon', 'freehand', name='geometry_type', schema='app', create_constraint=True), nullable=False),
    sa.Column('geometry_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app.users.id'], ),
    sa.ForeignKeyConstraint(['defect_class_id'], ['app.defect_classes.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['app.images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_annotations_defect_class_id'), 'annotations', ['defect_class_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_annotations_geometry_type'), 'annotations', ['geometry_type'], unique=False, schema='app')
    op.create_index(op.f('ix_app_annotations_image_id'), 'annotations', ['image_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_annotations_severity'), 'annotations', ['severity'], unique=False, schema='app')
    # ### end Alembic commands ###

    op.bulk_insert(defect_classes_table, DEFECT_CLASS_SEED)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_annotations_severity'), table_name='annotations', schema='app')
    op.drop_index(op.f('ix_app_annotations_image_id'), table_name='annotations', schema='app')
    op.drop_index(op.f('ix_app_annotations_geometry_type'), table_name='annotations', schema='app')
    op.drop_index(op.f('ix_app_annotations_defect_class_id'), table_name='annotations', schema='app')
    op.drop_table('annotations', schema='app')
    op.drop_index(op.f('ix_app_images_status'), table_name='images', schema='app')
    op.drop_index(op.f('ix_app_images_dataset_id'), table_name='images', schema='app')
    op.drop_table('images', schema='app')
    op.drop_table('datasets', schema='app')
    op.drop_table('users', schema='app')
    op.drop_table('defect_classes', schema='app')
    # ### end Alembic commands ###

    op.execute("DROP SCHEMA IF EXISTS app CASCADE")
